package com.mehmetari.hrms.entity;
public enum City {
        ADANA("adana"),
        ADIYAMAN("adıyaman"),
        AFYONKARAHISAR("afyonkarahisar"),
        AGRI("ağrı"),
        AMASYA("amasya"),
        ANKARA("ankara"),
        ANTALYA("antalya"),
        ARTVIN("artvin"),
        AYDIN("aydın"),
        BALIKESIR("balıkesir"),
        BILECIK("bilecik"),
        BINGOL("bingöl"),
        BITLIS("bitlis"),
        BOLU("bolu"),
        BURDUR("burdur"),
        BURSA("bursa"),
        CANAKKALE("canakkale"),
        CANKIRI("çankırı"),
        CORUM("çorum"),
        DENIZLI("denizli"),
        DIYARBAKIR("diyarbakır"),
        EDIRNE("edirne"),
        ELAZIG("elazıg"),
        ERZINCAN("erzincan"),
        ERZURUM("erzurum"),
        ESKISEHIR("eskişehir"),
        GAZIANTEP("gaziantep"),
        GIRESUN("giresun"),
        GUMUSHANE("gümüşhane"),
        HAKKARI("hakkari"),
        HATAY("hatay"),
        ISPARTA("ısparta"),
        MERSIN("mersin"),
        ISTANBUL("istanbul"),
        IZMIR("izmir"),
        KARS("kars"),
        KASTAMONU("kastamonu"),
        KAYSERI("kayseri"),
        KIRKLARELI("kırklareli"),
        KIRSEHIR("kırşehir"),
        KOCAELI("kocaeli"),
        KONYA("konya"),
        KUTAHYA("kütahya"),
        MALATYA("malatya"),
        MANISA("manisa"),
        KAHRAMANMARAS("kahramanmaras"),
        MARDIN("mardin"),
        MUGLA("mugla"),
        MUS("muş"),
        NEVSEHIR("nevşehir"),
        NIGDE("niğde"),
        ORDU("ordu"),
        RIZE("rize"),
        SAKARYA("sakarya"),
        SAMSUN("samsun"),
        SIIRT("siirt"),
        SINOP("sinop"),
        SIVAS("sivas"),
        TEKIRDAG("tekirdağ"),
        TOKAT("tokat"),
        TRABZON("trabzon"),
        TUNCELI("tunceli"),
        SANLIURFA("şanlıurfa"),
        USAK("uşak"),
        VAN("van"),
        YOZGAT("yozgat"),
        ZONGULDAK("zonguldak"),
        AKSARAY("aksaray"),
        BAYBURT("bayburt"),
        KARAMAN("karaman"),
        KIRIKKALE("kırıkkale"),
        BATMAN("batman"),
        SIRNAK("şırnak"),
        BARTIN("bartın"),
        ARDAHAN("ardahan"),
        IGDIR("ığdır"),
        YALOVA("yalova"),
        KARABUK("karabük"),
        KILIS("kilis"),
        OSMANIYE("osmaniye"),
        DUZCE("düzce");

    private final String city;

    City(String city) {
        this.city = city;
    }

    public String getCity() {
        return city;
    }
}
